const products = [
  {
    title: "Men Classic Formal Dress",
    description: "Classic formal dress for men suitable for office and events.",
    price: 1999,
    category: "dress",
    gender: "men",
    tags: ["trending"],
    image: "src/assets/products/men_dress1.jpg",
    stock: 15,
  },
  {
    title: "Men Casual Summer Shirt Dress",
    description: "Lightweight casual summer shirt dress for daily wear.",
    price: 1499,
    category: "dress",
    gender: "men",
    tags: ["newlyArrived"],
    image: "src/assets/products/men_dress2.jpg",
    stock: 20,
  },
  {
    title: "Women Floral Summer Dress",
    description: "Floral printed summer dress with breathable fabric.",
    price: 1799,
    category: "dress",
    gender: "women",
    tags: ["trending", "discounted"],
    image: "src/assets/products/women_dress1.jpg",
    stock: 12,
  },
  {
    title: "Women Elegant Party Dress",
    description: "Elegant party dress designed for evening occasions.",
    price: 2499,
    category: "dress",
    gender: "women",
    tags: ["trending"],
    image: "src/assets/products/women_dress2.jpg",
    stock: 10,
  },
  {
    title: "Women Casual Cotton Dress",
    description: "Comfortable cotton dress perfect for casual wear.",
    price: 1299,
    category: "dress",
    gender: "women",
    tags: ["newlyArrived"],
    image: "src/assets/products/women_dress3.jpg",
    stock: 18,
  },
  {
    title: "Kids Birthday Party Dress",
    description: "Cute birthday party dress for kids.",
    price: 999,
    category: "dress",
    gender: "kids",
    tags: ["trending"],
    image: "src/assets/products/kids_dress1.jpg",
    stock: 25,
  },
  {
    title: "Kids Cartoon Printed Dress",
    description: "Cartoon printed fun dress for kids everyday wear.",
    price: 799,
    category: "dress",
    gender: "kids",
    tags: ["discounted"],
    image: "src/assets/products/kids_dress2.jpg",
    stock: 30,
  },
  {
    title: "Men Linen Beach Dress",
    description: "Linen beach dress ideal for summer vacations.",
    price: 1699,
    category: "dress",
    gender: "men",
    tags: ["newlyArrived", "trending"],
    image: "src/assets/products/men_dress3.jpg",
    stock: 14,
  },
  {
    title: "Women Boho Maxi Dress",
    description: "Boho style maxi dress with elegant flowy design.",
    price: 2199,
    category: "dress",
    gender: "women",
    tags: ["trending"],
    image: "src/assets/products/women_dress4.jpg",
    stock: 9,
  },
  {
    title: "Kids Winter Warm Dress",
    description: "Warm winter dress for kids suitable for cold weather.",
    price: 1199,
    category: "dress",
    gender: "kids",
    tags: ["newlyArrived"],
    image: "src/assets/products/kids_dress3.jpg",
    stock: 22,
  },
];

module.exports = products;
