export const products = [
  {
    id: 1,
    title: "Men Classic Formal Dress",
    price: 1999,
    category: "dress",
    gender: "men",
    tags: ["trending"],
    image: "/src/assets/products/men_dress1.jpg",
    stock: 15,
  },
  {
    id: 2,
    title: "Men Casual Summer Shirt Dress",
    price: 1499,
    category: "dress",
    gender: "men",
    tags: ["new"],
    image: "/src/assets/products/men_dress2.jpg",
    stock: 20,
  },
  {
    id: 3,
    title: "Women Floral Summer Dress",
    price: 1799,
    category: "dress",
    gender: "women",
    tags: ["trending", "sale"],
    image: "/src/assets/products/women_dress1.jpg",
    stock: 12,
  },
  {
    id: 4,
    title: "Women Elegant Party Dress",
    price: 2499,
    category: "dress",
    gender: "women",
    tags: ["trending"],
    image: "/src/assets/products/women_dress2.jpg",
    stock: 10,
  },
  {
    id: 5,
    title: "Women Casual Cotton Dress",
    price: 1299,
    category: "dress",
    gender: "women",
    tags: ["new"],
    image: "/src/assets/products/women_dress3.jpg",
    stock: 18,
  },
  {
    id: 6,
    title: "Kids Birthday Party Dress",
    price: 999,
    category: "dress",
    gender: "kids",
    tags: ["trending"],
    image: "/src/assets/products/kids_dress1.jpg",
    stock: 25,
  },
  {
    id: 7,
    title: "Kids Cartoon Printed Dress",
    price: 799,
    category: "dress",
    gender: "kids",
    tags: ["sale"],
    image: "/src/assets/products/kids_dress2.jpg",
    stock: 30,
  },
  {
    id: 8,
    title: "Men Linen Beach Dress",
    price: 1699,
    category: "dress",
    gender: "men",
    tags: ["new", "trending"],
    image: "/src/assets/products/men_dress3.jpg",
    stock: 14,
  },
  {
    id: 9,
    title: "Women Boho Maxi Dress",
    price: 2199,
    category: "dress",
    gender: "women",
    tags: ["trending"],
    image: "/src/assets/products/women_dress4.jpg",
    stock: 9,
  },
  {
    id: 10,
    title: "Kids Winter Warm Dress",
    price: 1199,
    category: "dress",
    gender: "kids",
    tags: ["new"],
    image: "/src/assets/products/kids_dress3.jpg",
    stock: 22,
  },
];
